/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://y7dssa7dybevjghqqvekpphyv4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-palumcigrrcmpi4kr4ph2lv4q4",
    "aws_cognito_identity_pool_id": "eu-west-1:70007fcd-c256-4869-bae4-5e4fa2cf154a",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_EqWmMCe9c",
    "aws_user_pools_web_client_id": "3050lbq7hurgk387l39fq9e2k5",
    "oauth": {
        "domain": "4lc0s15xmxfe-staging.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://,exp://127.0.0.1:19000/--/",
        "redirectSignOut": "myapp://,exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "befitfitnesstrackere76cd36965514a57a87ce95be0c963454-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
